# -*- coding: utf-8 -*-
"""bar_graph_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3pf2LbXA3JqFvoKTKPL6W8Q7Hw7I3q-
"""

import matplotlib.pyplot as plt
import numpy as np

# Policies / models
policies = [
    "Baseline",
    "Prosodic",
    "LB",
    "SM",
    "LD",
    "SS",
    "Phoneme"
]

# Test error rates (%)
test_wer = [26.33, 14.59, 12.30, 12.17, 13.71, 12.35, 13.43]
test_cer = [6.65, 4.14, 3.61, 3.59, 3.78, 3.56, 4.17]

# X positions
x = np.arange(len(policies))
width = 0.35

# Create figure
fig, ax = plt.subplots(figsize=(12, 6))

# Bars
bars1 = ax.bar(x - width/2, test_wer, width, label='Test WER')
bars2 = ax.bar(x + width/2, test_cer, width, label='Test CER')

# Labels and title
ax.set_xlabel('Augmentation Policy')
ax.set_ylabel('Error Rate (%)')
ax.set_title('UASpeech Error Rates by Augmentation Policy')
ax.set_xticks(x)
ax.set_xticklabels(policies)
ax.legend()

# Add values on top of bars
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width()/2,
            height + 0.5,
            f'{height:.2f}%',
            ha='center',
            va='bottom',
            fontsize=8
        )

plt.tight_layout()
plt.show()